platform :ios, '7.0'

target "DecouplingKitExample" do
	pod 'DecouplingKit', :path=>'../../DecouplingKit’
    pod 'Bussiness1', :path=>'../Bussiness1’
    pod 'Bussiness2', :path=>'../Bussiness2’
    pod 'BussinessPublicService', :path=>'../BussinessPublicService’

end