platform :ios, '7.0'

target "Bussiness2" do
	pod 'DecouplingKit', :path=>'../../’
    pod 'BussinessPublicService', :path=>'../BussinessPublicService’
    #pod 'Bussiness2', :path=>'/Users/youku/Music/github/DecouplingKit1/Bussiness2’

end
